export const BANNER = {
  main: '상조보험이 막막한 당신을 위해.',
  sub: ['어떻게 선택할 지 어려운 상조보험,', 'Mamoori가 한눈에 볼 수 있도록 모았습니다.'],
};

export const INSURANCE = [
  {
    company: '보람상조',
    serviceName: '마이스터35',
    description:
      '믿을 수 있는 보람상조의 프리미엄 베스트 상품으로 월 35,000원에 장례토탈 서비스를 제공합니다.	- 월 35,000원 × 143회',
    price: '월 35,000원',
    totalPrice: '4,990,000원',
    imgUrl: 'https://www.boram.com/images/client/pc/img/funeral/label-m35.png',
    link: 'https://www.boram.com/Funeral/Catalog/Products/M35',
  },
  {
    company: '보람상조',
    serviceName: '마이스터40',
    description:
      '믿을 수 있는 보람상조의 프리미엄 베스트 상품으로 월 40,000원에 장례토탈 서비스를 제공합니다.	- 월 40,000원 × 150회',
    price: '월 40,000원',
    totalPrice: '5,990,000원',
    imgUrl: 'https://www.boram.com/images/client/pc/img/funeral/label-m40.png',
    link: 'https://www.boram.com/Funeral/Catalog/Products/M40',
  },
  {
    company: '예다함',
    serviceName: '예다함 396',
    description: '실속형 상품',
    price: '100회 39,600원',
    totalPrice: '3,960,000원',
    imgUrl: 'https://www.yedaham.co.kr/images/product/product/img_yedahamS396.png',
    link: 'https://www.yedaham.co.kr/product/product/yedahamS396.do',
  },
  {
    company: '예다함',
    serviceName: '예다함 VIP',
    description: '차원이 다른 서비스를 제공하는 프리미엄 상품',
    price: '120회 83,340원',
    totalPrice: '10,000,000원',
    imgUrl: 'https://www.yedaham.co.kr/images/product/product/vis_yedahamvip.png',
    link: 'https://www.yedaham.co.kr/product/product/yedahamVIP.do',
  },
  {
    company: '평화상조',
    serviceName: '평화400',
    description: '평화상조는 고품질·합리적인 가격으로 차별화된 서비스를 제공합니다.',
    price: '100회 40,000 원',
    totalPrice: '4,000,000 원',
    imgUrl: 'https://www.phnuri.co.kr/_00.upload/ckImgReal/p04/cntsImg/20170423/basic400_new.jpg',
    link: 'https://www.phnuri.co.kr/phgrp/cnts/CntsFrntView.do?cntsId=CFV_2010100&menuNo=2010100',
  },
  {
    company: '평화상조',
    serviceName: '실속495',
    description: '평화상조는 고품질·합리적인 가격으로 차별화된 서비스를 제공합니다',
    price: '100회 49,500 원',
    totalPrice: '4,950,000 원',
    imgUrl: 'https://www.phnuri.co.kr/_00.upload/ckImgReal/p04/cntsImg/20170423/basic495_new.jpg',
    link: 'https://www.phnuri.co.kr/phgrp/cnts/CntsFrntView.do?cntsId=CFV_2010200&menuNo=2010200',
  },
  {
    company: '한라상조',
    serviceName: '한라 994',
    description: '최상의 서비스와 품격을 모두 갖춘 고품격 고객 서비스',
    price: '140회 71000원',
    totalPrice: '9,940,000원',
    imgUrl: 'https://www.hanlasangjo.com/images/product/img1_1_1.png',
    link: 'https://www.hanlasangjo.com/product/funeral994.asp',
  },
  {
    company: '한라상조',
    serviceName: '한라 483',
    description: '최상의 서비스와 품격을 모두 갖춘 고품격 고객 서비스',
    price: '140회 34500원',
    totalPrice: '4,830,000원',
    imgUrl: 'https://www.hanlasangjo.com/images/product/img1_1_3.png',
    link: 'https://www.hanlasangjo.com/product/funeral483.asp',
  },
  {
    company: '부모사랑',
    serviceName: '라이프 390',
    description: '월 3만원대로 준비하는 라이프 플랜',
    price: '월 39,0000원',
    totalPrice: '3,900,000원',
    imgUrl: 'https://www.bumo-sarang.com/upload/product/life390web(1).jpg',
    link: 'https://www.bumo-sarang.com/sub03/sub03_02.html?uid=66&product_gubun=',
  },
  {
    company: '부모사랑',
    serviceName: '뉴 라이프캐시백 10',
    description: '돌려받자! 10만원 부모사랑 캐시백',
    price: '월 500,000원',
    totalPrice: '5,000,000원',
    imgUrl: 'https://www.bumo-sarang.com/upload/product/newcachback10_web(1).jpg',
    link: 'https://www.bumo-sarang.com/sub03/sub03_02.html?uid=87&product_gubun=1',
  },
  {
    company: '교원라이프',
    serviceName: '교원라이프 399',
    description: '삶의 희로애락을 함께하는 토탈 라이프케어 서비스',
    price: '월 26,600원',
    totalPrice: '3,990,000원',
    imgUrl:
      'http://www.kyowonlife.co.kr/upload/prdtLifeGoods/bedc59ee-a631-42a8-87d9-55f2cc3d0ff8.jpg',
    link: 'http://www.kyowonlife.co.kr/Service/ProductView?categoryCd=04&basiSeq=1',
  },
  {
    company: '교원라이프',
    serviceName: '교원라이프 499',
    description: '삶의 희로애락을 함께하는 토탈 라이프케어 서비스',
    price: '월 28,300원, 월 33,300원',
    totalPrice: '4,990,000원',
    imgUrl:
      'http://www.kyowonlife.co.kr/upload/prdtLifeGoods/00a746e3-13bd-4d65-8790-20e730090ede.jpg',
    link: 'http://www.kyowonlife.co.kr/Service/ProductView?categoryCd=04&basiSeq=10',
  },
  {
    company: '프리드라이프',
    serviceName: '늘 함께',
    description: '원하는 상품과 알찬 할인을 제공합니다',
    price: '24,000원',
    totalPrice: '3,600,000원',
    imgUrl:
      'https://lh3.googleusercontent.com/y2PSDAAL3zqtCmq5CHq18qWmIXZixav_e07CTUoq817iHfWP0g5dZk7coBL-g2ejwR0Q3EwDb30DywvZput9awPMfld8fxy4_E4pdu5jRJvo-PwNP1TH=w800',
    link: 'https://preed-life.co.kr/INTRO/view/1832388',
  },

  {
    company: '프리드라이프',
    serviceName: '늘 정성',
    description: '정성을 다하는 진심어린 서비스를 제공합니다',
    price: '28,000원',
    totalPrice: '4,200,000원',
    imgUrl:
      'https://lh3.googleusercontent.com/IevLVg_mIvoNQ9z4dc3FROow__et1ET6lYKJzBvgfeF6jHDsiQUGrgTrZ_y-LB4s8krvFi81SLPyjKQ5mnYoWgvFg6R6qARXSF-AQZ_T_fRSK8R8ONMNxvw=w800',
    link: 'https://preed-life.co.kr/INTRO/view/2557335',
  },
  {
    company: '프리드라이프',
    serviceName: '늘 만족',
    description: '처음부터 끝까지 체계적인 지원으로 든든한 서비스를 제공합니다',
    price: '월 32,000원',
    totalPrice: '4,800,000원',
    imgUrl:
      'https://lh3.googleusercontent.com/_RmvcInEs5hDFc4-KniOxjXy2dxFrEpG4Q77c2zKtiqgksf7tgyHeJ5TlVvpp1i9z2gsrlt_YkoU-JFuvES16EaC_XCWTKuvc838itq51Pclriaj9zfL=w800',
    link: 'https://preed-life.co.kr/INTRO/view/2557354',
  },
  {
    company: '더리본',
    serviceName: '290상품',
    description: '더리본의 290상품입니다',
    price: '월 29,000원',
    totalPrice: '2,900,000',
    imgUrl: 'https://the-reborn.co.kr/images/product/banner_02.jpg',
    link: 'https://the-reborn.co.kr/product/funeral.asp',
  },
  {
    company: '더리본',
    serviceName: '390상품',
    description: '더리본의 390상품입니다',
    price: '월 30,000원',
    totalPrice: '3,900,000',
    imgUrl: 'https://the-reborn.co.kr/images/product/banner_02.jpg',
    link: 'https://the-reborn.co.kr/product/funeral.asp',
  },
  {
    company: '더리본',
    serviceName: '420상품',
    description: '더리본의 420상품입니다',
    price: '월 30,000원',
    totalPrice: '4,200,000',
    imgUrl: 'https://the-reborn.co.kr/images/product/banner_02.jpg',
    link: 'https://the-reborn.co.kr/product/funeral.asp',
  },
  {
    company: '더리본',
    serviceName: '520상품',
    description: '더리본의 520상품입니다',
    price: '월 40,000원',
    totalPrice: '5,200,000',
    imgUrl: 'https://the-reborn.co.kr/images/product/banner_02.jpg',
    link: 'https://the-reborn.co.kr/product/funeral.asp',
  },
];
